[build]
  functions = "/functions"

[[scheduled_functions]]
  path = "/.netlify/functions/updateCount"
  schedule = "0 * * * *" # This cron syntax means the function will run at the top of every hour
